seo:
  site_name: ViaSana Portfolio
  title: ViaSana | Web Dev Co-Op
  description:
  keywords:
  social_image: assets/images/icons/IG_profile.jpg
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
